HOROVOD_CUDA_HOME=/usr/local/cuda HOROVOD_NCCL_INCLUDE=/usr/include HOROVOD_NCCL_LIB=/usr/lib HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_WITH_PYTORCH=1 poetry add horovod

#HOROVOD_CUDA_HOME=/usr/local/cuda HOROVOD_NCCL_INCLUDE=/usr/include HOROVOD_NCCL_LIB=/usr/lib HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_WITH_PYTORCH=1 pip install horovod --no-cache-dir

#HOROVOD_CUDA_HOME=/usr/local/cuda HOROVOD_NCCL_INCLUDE=/usr/include HOROVOD_NCCL_LIB=/usr/lib HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_WITH_PYTORCH=1 pip install horovod --no-cache-dir

